name: anime
adopt-info: anime
summary: Anime scenes from terminal
description: |
  Anime scenes from terminal

base: core22
grade: stable
confinement: strict

license: MIT

apps: 
  anime:
    command: anime
    environment: 
      LC_ALL: C.UTF-8

parts:
  anime:
    source: https://github.com/arman0333/anime-cli
    source-type: git
    plugin: python
    python-version: python3

    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version "$(git describe --tags | sed 's/^v//' | cut -d "-" -f1)"

    build-packages:
      - python3
    stage-packages:
      - python3
